### PR TITLE
fix: lint, quality, typings

### PR DESCRIPTION
**Pull request by Socketlike**
This is a work-in-progress. DO NOT MERGE UNTIL FINISHED.

### CODE REVIEW

**Comment by Socketlike** [comment]
Progress update

**Comment by Socketlike** [comment]
> https://github.com/WolfPlugs/HolyNotes/blob/main/src/noteHandler/utils.ts#L16-L26

There is a built-in exposed clipboard utility on `window` called `DiscordNative.clipboard`.
Why didn't you use that?

**Comment by Socketlike** [comment]
Fully complete now. Just needs testing.

**Comment by Socketlike** [comment]
Tested build. Fully working except for a few styling quirks.

**Comment by ArjixWasTaken** [comment]
Once this is done, can I port it to Vencord?
I'll give credit ofc.

**Comment by Socketlike** [comment]
Crashes on sort is fixed.

**Comment by Wolfkid200444** [comment]
> Once this is done, can I port it to Vencord? I'll give credit ofc.

Yeah u can

**Comment by Wolfkid200444** [comment]
Theres seems to be some conflicts which must be resolved

**Pull request closed without merging**
